services:
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/en9ng8:QaRM8t
  name: tpsulvoomfvu
  numInstances: 1
  plan: free
  region: ohio
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/u64mc:NPyE8
  name: uvozcmytgexlzgqrq
  numInstances: 1
  plan: free
  region: ohio
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/howh5lg:fFgPyqv
  name: tgpgnsfflty
  numInstances: 1
  plan: free
  region: ohio
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/rbdelh:P1s26Q
  name: onfkvkchndlgtdeh
  numInstances: 1
  plan: free
  region: ohio
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/pexvvn49s:qlKaWsWdx
  name: ucxrvayxru
  numInstances: 1
  plan: free
  region: ohio
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/l1skk9:gcz8o7
  name: axpmtdslpp
  numInstances: 1
  plan: free
  region: ohio
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/w3b70eyl:FOGgdtfR
  name: drpbglnlowkxcytn
  numInstances: 1
  plan: free
  region: ohio
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/mvv1pktr:8lpxny52
  name: uwlxhtkbqi
  numInstances: 1
  plan: free
  region: ohio
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/wmhuhcd:k4P0tGY
  name: mnbmunvcaymdsopvh
  numInstances: 1
  plan: free
  region: ohio
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/ipgc9:BaaWA
  name: ixoxawgiqbtlqkhub
  numInstances: 1
  plan: free
  region: ohio
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/mc5gv:DKsfm
  name: gnsnqhywveranirui
  numInstances: 1
  plan: free
  region: ohio
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/ggerutab:HWhfGf3T
  name: pxuzovnsxasrgbmgk
  numInstances: 1
  plan: free
  region: ohio
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/sezse6:5InbwQ
  name: qpytbrznnmo
  numInstances: 1
  plan: free
  region: ohio
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/8xudd34ose:dmGIBV3rC0
  name: zlcxdmiqfle
  numInstances: 1
  plan: free
  region: ohio
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/fasulxf761:yV9cLcGrub
  name: dcumofwzzoivfwgz
  numInstances: 1
  plan: free
  region: ohio
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/fvoczikg:lT3hX2qA
  name: ktqugmddzdw
  numInstances: 1
  plan: free
  region: ohio
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/t96yk9:1mTSHh
  name: gvpbvlnfzoge
  numInstances: 1
  plan: free
  region: ohio
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/il3wggolvi:uaqOUxMbxh
  name: iuuqmxdesfbxxm
  numInstances: 1
  plan: free
  region: ohio
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/hdkdlw:nxmhA9
  name: gzglhnegzr
  numInstances: 1
  plan: free
  region: ohio
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/o8nbybqfu:zUbIYh5Yd
  name: ehwoklkkfio
  numInstances: 1
  plan: free
  region: ohio
  type: web
