services:
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: rgtrhtyhyjyujuy
  numInstances: null
  plan: free
  region: ohio
  repo: null
  rootDir: GUmIZE
  type: web