services:
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: juirt-grtjihotrj
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: OhCLn9Zhy
  type: web