services:
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/qlhge7vy:9l7PGcmz
  name: coourcoegoqlvrg
  numInstances: 1
  plan: free
  region: oregon
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/ynryxxb:tg6R2pV
  name: npzbeelnbavpuin
  numInstances: 1
  plan: free
  region: oregon
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/qgag23:Zibq5v
  name: mmohsmqlhndnh
  numInstances: 1
  plan: free
  region: oregon
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/ff1smisusx:BQdVWy4y2P
  name: susqahhswcuu
  numInstances: 1
  plan: free
  region: oregon
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/vvfevkqrtw:v371qMrKxr
  name: kvurnptgumpgzys
  numInstances: 1
  plan: free
  region: oregon
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/5qane:UnOQI
  name: kpzgqdlchofhqvi
  numInstances: 1
  plan: free
  region: oregon
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/hcgkc:UX41r
  name: nvvdfdcsagiutll
  numInstances: 1
  plan: free
  region: oregon
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/xpenhnr:yKRiExH
  name: hooiqgsphrplnp
  numInstances: 1
  plan: free
  region: oregon
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/qvzdi7agc:YV4cSOHEP
  name: evnkkiizwvsxzik
  numInstances: 1
  plan: free
  region: oregon
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/2g5r4:pGSE7
  name: imgqtkngzgiee
  numInstances: 1
  plan: free
  region: oregon
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/dpblypcnb:mOaiKpmRI
  name: kviycexiyraqiym
  numInstances: 1
  plan: free
  region: oregon
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/pqr1c0mxmb:UD0vEZVIPX
  name: aeibgheurnsdtzzp
  numInstances: 1
  plan: free
  region: oregon
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/xpuvknw:YI3uUHF
  name: cnggikmzpygonf
  numInstances: 1
  plan: free
  region: oregon
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/zodd3stkpz:4TrMoGKIte
  name: pkxnqatenlnwsh
  numInstances: 1
  plan: free
  region: oregon
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/xpguzareyc:gyZ5g9wCBL
  name: aksehrfqnfyx
  numInstances: 1
  plan: free
  region: oregon
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/xktips:O3GnMM
  name: fbgtixwlcxuzu
  numInstances: 1
  plan: free
  region: oregon
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/stx6quwuo:wLl9ggSzc
  name: epmqbinbnvlgl
  numInstances: 1
  plan: free
  region: oregon
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/grgnqcwv:fHdGsk8k
  name: msgrlwvshoagno
  numInstances: 1
  plan: free
  region: oregon
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/d6sci:GAgNT
  name: kernkubknxdexu
  numInstances: 1
  plan: free
  region: oregon
  type: web
- autoDeploy: false
  env: image
  image:
    url: docker.io/lxacs/1ylfv:2o4OI
  name: qlfvkuwkqpxno
  numInstances: 1
  plan: free
  region: oregon
  type: web
