services:
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: klgenzgzzb
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: VNPhYILu
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: dwqveeiuzthong
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: TTlEiCl1f
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: cgnitlxyckcf
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: zlO6qze
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: teggarrrgfqqcs
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: 9bp56Q
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: akwcaxyallry
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: 7m5Rz50NL
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: mzeiptwwlhfghbd
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: OXDbGnewc
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: butrcwxpxoliu
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: vG4cTCY7
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: asxckpfyapgtghnk
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: yDrIZfCX
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: zsvcmsgflvbvmsvco
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: vMcZnIhRQ7
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: nmiimfaasoktl
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: fnqpA
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: gigiemuexh
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: GUmIZE
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: bcuvtyodqz
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: uoEDr3bzwM
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: ztctunqboro
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: nep9l5g5
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: zbuotrhmzhvzie
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: Tt6kyu
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: dgcvtwglkrepgvgg
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: xOGYSagwX8
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: wrqsnpgckxvh
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: uHdRD
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: dkrcyhhmwh
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: zMpdR308
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: kwsewpvdvnzplizao
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: PU41QKMc
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: rgodnpnthxvipop
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: 2aVQFuHlgg
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: gbygvnpuzvwggg
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: bN5fw
  type: web
