services:
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: otcvxcnzgigc
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: VNPhYILu
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: nxodlsetoypzfghla
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: TTlEiCl1f
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: mhyscgwlppdnqo
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: zlO6qze
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: bzdqmnzbrwayedfa
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: 9bp56Q
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: zxslslmwrbgfzr
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: 7m5Rz50NL
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: pyzmuzivgofhyazgy
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: OXDbGnewc
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: isxobzfllgungxcca
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: vG4cTCY7
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: ixnixedwri
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: yDrIZfCX
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: yprktweszqryy
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: vMcZnIhRQ7
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: dccgslxoqbg
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: fnqpA
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: wmuexcehlyv
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: GUmIZE
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: kpyvcuvxal
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: uoEDr3bzwM
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: zvmqdffcovgghoraw
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: nep9l5g5
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: bslggchaik
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: Tt6kyu
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: lwwcesihylgm
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: xOGYSagwX8
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: sgnvuggxzofdef
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: uHdRD
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: uswgwxspwt
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: zMpdR308
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: vtsttculgx
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: PU41QKMc
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: zyisozebtd
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: 2aVQFuHlgg
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  name: eqplwellusxx
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: bN5fw
  type: web
