services:
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: qgnmvzynkbzdanule
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: VNPhYILu
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: ikglmkgpcusl
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: TTlEiCl1f
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: xilvnhweqpfkp
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: zlO6qze
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: rtkxhohgxiw
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: 9bp56Q
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: scafffitzbksl
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: 7m5Rz50NL
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: hcilbdgseeegzhenz
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: OXDbGnewc
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: bnetggqiqyih
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: vG4cTCY7
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: vwritbickxamrmdc
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: yDrIZfCX
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: kxmggtycetwt
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: vMcZnIhRQ7
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: byqgaicuocs
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: fnqpA
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: ougigfslegtzmwrd
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: GUmIZE
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: gompzyypecsdlxn
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: uoEDr3bzwM
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: thycsylvlggvb
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: nep9l5g5
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: dwomliughebmtz
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: Tt6kyu
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: rytdzclbzqvgyhh
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: xOGYSagwX8
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: bzwqdrnhexyx
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: uHdRD
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: vmfoxpeigbcesgndu
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: zMpdR308
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: kgrgatfytgkr
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: PU41QKMc
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: qweukkrswz
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: 2aVQFuHlgg
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: ksidwtskzb
  numInstances: null
  plan: free
  region: singapore
  repo: null
  rootDir: bN5fw
  type: web
