services:
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: qsmmzxemtgfbpf
  numInstances: null
  plan: free
  region: oregon
  repo: null
  rootDir: qAwEx4cm
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: dwlqcsrfsfogcthma
  numInstances: null
  plan: free
  region: oregon
  repo: null
  rootDir: kyxCQKN
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: dvsgpxzuyre
  numInstances: null
  plan: free
  region: oregon
  repo: null
  rootDir: k2p31b
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: opelxwqlyzcgw
  numInstances: null
  plan: free
  region: oregon
  repo: null
  rootDir: Ac198P0mia
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: aylgowhwwnmksho
  numInstances: null
  plan: free
  region: oregon
  repo: null
  rootDir: o44gtQf4Au
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: agyfbgdogs
  numInstances: null
  plan: free
  region: oregon
  repo: null
  rootDir: 8rDoz
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: hmhhrbrsgnztisbf
  numInstances: null
  plan: free
  region: oregon
  repo: null
  rootDir: oCKVM
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: opgwckxsultu
  numInstances: null
  plan: free
  region: oregon
  repo: null
  rootDir: 7gGYlW5
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: fzklunskfwoifzdsg
  numInstances: null
  plan: free
  region: oregon
  repo: null
  rootDir: Yv0z7Iie2
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: ehlasdlyrh
  numInstances: null
  plan: free
  region: oregon
  repo: null
  rootDir: ibNCh
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: zpndgxumfgpzdcs
  numInstances: null
  plan: free
  region: oregon
  repo: null
  rootDir: NQ2zCfAZo
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: glraexblxaytvggt
  numInstances: null
  plan: free
  region: oregon
  repo: null
  rootDir: IBevMcA8gE
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: xkouqzpfgrnoroq
  numInstances: null
  plan: free
  region: oregon
  repo: null
  rootDir: HGgc0Tk
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: uhhgqeqwnaiy
  numInstances: null
  plan: free
  region: oregon
  repo: null
  rootDir: syY5WtCoMB
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: ixguvfkyoqav
  numInstances: null
  plan: free
  region: oregon
  repo: null
  rootDir: YxDY876QIw
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: tuofvmgtzd
  numInstances: null
  plan: free
  region: oregon
  repo: null
  rootDir: OlsvhO
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: fvtyzkpfbgse
  numInstances: null
  plan: free
  region: oregon
  repo: null
  rootDir: R2upYHeaM
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: dugkklkrrr
  numInstances: null
  plan: free
  region: oregon
  repo: null
  rootDir: KBobzcPG
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: hytrgvlqagt
  numInstances: null
  plan: free
  region: oregon
  repo: null
  rootDir: TVIIV
  type: web
- autoDeploy: false
  branch: main
  dockerCommand: null
  env: docker
  healthCheckPath: /
  name: hkvtqkqxmht
  numInstances: null
  plan: free
  region: oregon
  repo: null
  rootDir: YpAg2
  type: web
